### ISSUE TITLE
A TagSet hasTag TagSet

### ISSUE THREAD

**Issue by jbkoh** [BrickSchema/brick-owl-dl#2]
https://github.com/BrickSchema/brick-owl-dl/blob/master/Brick.ttl#L97

In this Restriction, it hasValue **brick**:Air, which should be **tag**:Air. I can look up later but want to leave a note so that I can remember.

**Comment by gtfierro** [comment]
This is not a bug. `brick.Air` is the substance; `tag.Air` is the tag

**Comment by jbkoh** [comment]
Objects of "hasValue" should be instances and brick.Air is a substance class or a TagSet. This restriction looks not right. I think we decided to instantiate Air in instance graphs.

**Comment by gtfierro** [comment]
The question of instances vs classes is orthogonal to the question of tags. We are using "punning" to treat substance classes as singleton instances. See the [relevant section of the README](https://github.com/BrickSchema/brick-owl-dl#substances). Can you be more specific about what's bothering you?

**Comment by jbkoh** [comment]
Sorry I was not specific enough. I remember our decision was to instantiate Substances in building graphs but not directly associating an instance to TagSets(==classes). Because of the decision, I even gave you SPARQL queries to automatically instantiate substances. Maybe you decided it alone and I lost the track. (or maybe I misunderstood the discussion.)

I am not sure if it is the right design choice especially because 1) we are introducing actual instances of substances in equipment input/output and 2) if we are punning for Substance classes only but not for the others, it is an inconsistent design.

**Comment by jbkoh** [comment]
```
:ts1    a       brick:Temperature_Sensor
:ts1    brick:measures      :Air
```
vs
```
:ts1    a       brick:Temperature_Sensor.
:ts1    brick:measures      :air1.
:air1   a       brick:Air.
```

**Comment by gtfierro** [comment]
Automatically instantiating substances creates more problems than it solves because it does not enforce that sensors/equipment/etc involving the same "chunk" of substance actually point to the same instance. We would need more nuanced inference in order to figure out, for example, that a sensor and a setpoint that are in the same room should be operating on the same instance of air. It would also be necessary to derive a set of rules for how big a "chunk" is: is it separated by walls? what about cubicles? glass? windows? Doing this properly requires more detail than we typically have in a Brick model. My thought was that assigning a *different* anonymous instance of a substance to every point or equipment causes more problem than it solves.

Additionally, introducing an UPDATE query for the purpose of making the model correct left a bad taste in my mouth. Part of the motivation for this particular formation is so a reasoner can follow OWL 2 DL semantics to properly fill in the model. Requiring an UPDATE query for this breaks that requirement.

What we are modeling with substances and points is different than the rest of what Brick is modeling because it is making statements about how _classes_ of points interact with _instances_ of substances. Punning solves the problem of how to name the instances of substances in a matter that is a) compatible with eventually creating specific instances of substances, and b) easily fulfilled under OWL 2 DL semantics. Simply put, I think its a better compromise than generating anonymous substance instances

**Comment by jbkoh** [comment]
I see that we were tackling different problems. To me, `:measures` was additional information that a modeler can put if needed, because hasTag seems to be enough for modeling TagSets. And the chunks are defined by the modeler as they design the system. I think it's enough we can model if two things measure symbolically the same substance. We have to find more concrete use cases, but I would like to at least have a room for the development of the idea. Especially, the idea of connecting different equipment, as Aslak exemplified, needs the concept of instances of substances.

But I totally understand that we'd better formally model a TagSet with its tags as well. And you'd like to explicitly say that Return_Air_Temp_Sensor measures Return_Air other than it hasTag Return and hasTag Air.

For more consistency and expressivity, I think we have to clearly distinguish between the instance-level relationship and class-level relationship, unless we discard either of them. And to me, the current :measures is a subPropertyOf :hasTag in terms of its functionality. It is modeling a class's concept. So your :measures should have a different name because it is read as instance level relationship. Maybe something like, "canMeasure"? I don't like to complicate the Brick properties, but it seems unavoidable. 

Otherwise, how would you distinguish between `:measures brick:Return_Air` and `:measures ex:ra1` if substances are meant to be instantiated? 
- Do you assume Substances cannot be instantiated?
- Otherwise, are we giving some flexibility about whether people choose `ex:ra1` or `brick:Return_Air`?


At the same time, I'd like to understand the motivation more clearly:
- How is it better than hasTag in terms of usage? What can "measures Return_Air" do while "hasTag Return, hasTag:Air" cannot do?

**Comment by gtfierro** [comment]
On Tue Jun 4, 2019 at 5:31 PM Jason Beomkyu Koh wrote:

I think I see where you're coming from here. I'm going to take a stab at
defining the two cases to make sure I'm understanding you while trying
to answer your question.

> Otherwise, how would you distinguish between `:measures brick:Return_Air` and `:measures ex:ra1` if substances are meant to be instantiated? 
> - Do you assume Substances cannot be instantiated?
> - Otherwise, are we giving some flexibility about whether people choose `ex:ra1` or `brick:Return_Air`?

The short answer is using the type punning allows both, so there is some
flexibility built in. While my examples below both use `:measures` as
the name of the property, I'm open to discussing having different names
for them. I do like having them be the same however.

`:measures brick:Return_Air` is a statement about the individuals
(instances) of the class in general.  For example, `:measures
brick:Returns_Air` describes the set of things that measure air used in
the "return" part of a process (which is given by the definition of
`brick:Returns_Air`) and lets users query for things that relate to that
concept. A reasoner can add the `:measures brick:Return_Air` property to
instances of the proper classes (e.g. `brick:Return_Air_Temperature_Sensor`).
This is already implemented in the ontology.

`:measures ex:ra1` is complementary to this and is not excluded by the
current design. `:measures ex:ra1` models which *specific* instance of
`brick:Return_Air` is being measured. This is absolutely something that
a modeler can add if needed, and wouldn't be able to be inferred by a
reasoner. 

These are both strictly more expressive and powerful than just having
the `air` and `return` tags. Tags alone have absolutely no context as to
how they are intended. Having the `return` and `air` tags is true for
`Return_Air_Temperature_Sensor`s, instances of `Return_Air`,
`Return_Air_Fan`s, `Return_Air_Damper`s, etc. Its important that we keep
the tags for purposes of discovery + compatibility with tag-based
systems such as Haystack.

Querying the two cases (`:measures brick:Return_Air` and `:measures
ex:ra1`) is a little different, but I think it to works to our benefit.
To find points that measure properties of Return Air, we query

```sparql
SELECT ?point WHERE {
    ?point  rdf:type    :Point .
    ?point  :measures   :Return_Air
}
```

Because of the reasoner, the `:measures brick:Return_Air` property
is added to all of the appropriate point instances. This includes points
who have `:measures ex:ra1`.

If we only want to find points that measure specific instances of Return
Air, we query

```sparql
SELECT ?point WHERE {
    ?point  rdf:type    :Point .
    ?point  :measures   ?substance_instance .
    ?substance_instance   rdf:type   :Return_Air
}
```

**Comment by gtfierro** [comment]
Responding from email doesn't get you Markdown, evidently! Let me repost that

**Comment by gtfierro** [comment]
I think I see where you're coming from here. I'm going to take a stab at defining the two cases to make sure I'm understanding you while trying to answer your question.

>  Otherwise, how would you distinguish between `:measures brick:Return_Air` and `:measures ex:ra1` if substances are meant to be instantiated?
>  - Do you assume Substances cannot be instantiated?
>  - Otherwise, are we giving some flexibility about whether people choose `ex:ra1` or `brick:Return_Air`?

The short answer is using the type punning allows both, so there is some flexibility built in. While my examples below both use `:measures` as the name of the property, I'm open to discussing having different names for them. I do like having them be the same however.

`:measures brick:Return_Air` is a statement about the individuals (instances) of the class in general.  For example, `:measures brick:Returns_Air` describes the set of things that measure air used in
the "return" part of a process (which is given by the definition of `brick:Returns_Air`) and lets users query for things that relate to that concept. A reasoner can add the `:measures brick:Return_Air` property to instances of the proper classes (e.g. `brick:Return_Air_Temperature_Sensor`).
This is already implemented in the ontology.

`:measures ex:ra1` is complementary to this and is not excluded by thecurrent design. `:measures ex:ra1` models which *specific* instance of`brick:Return_Air` is being measured. This is absolutely something that a modeler can add if needed, and wouldn't be able to be inferred by a reasoner.

These are both strictly more expressive and powerful than just having the `air` and `return` tags. Tags alone have absolutely no context as to how they are intended. Having the `return` and `air` tags is true for `Return_Air_Temperature_Sensor`s, instances of `Return_Air`, `Return_Air_Fan`s, `Return_Air_Damper`s, etc. Its important that we keep the tags for purposes of discovery + compatibility with tag-based systems such as Haystack.

Querying the two cases (`:measures brick:Return_Air` and `:measures ex:ra1`) is a little different, but I think it to works to our benefit. To find points that measure properties of Return Air, we query

```sparql
SELECT ?point WHERE {
    ?point  rdf:type    :Point .
    ?point  :measures   :Return_Air
}
```

Because of the reasoner, the `:measures brick:Return_Air` property is added to all of the appropriate point instances. This includes points who have `:measures ex:ra1`.

If we only want to find points that measure specific instances of Return Air, we query

```sparql
SELECT ?point WHERE {
    ?point  rdf:type    :Point .
    ?point  :measures   ?substance_instance .
    ?substance_instance   rdf:type   :Return_Air
}
```

**Comment by gtfierro** [comment]
Is there more we want to discuss here? Or can I close this issue?

**Comment by jbkoh** [comment]
I am fine with this direction at least for now.

**Comment by jbkoh** [comment]
Maybe we can even allow punning for all the relationships to ease the tagging. (e.g., :znt1 isPointOf brick:VAV.)
